#!/usr/bin/env python3
"""cuda-compat: will this image's CUDA userspace run on a node with this driver?

Answers the question nvidia-container-cli answers at container start, without a
node: it evaluates the image's NVIDIA_REQUIRE_* expressions against a stated set
of node facts, using a faithful port of libnvidia-container's own DSL evaluator
(src/cli/dsl.c: dsl_evaluate / dsl_compare_version / dsl_compare_string, plus the
four rules src/cli/configure.c registers). tests/oracle/ holds a golden table
generated by compiling that C code verbatim; test_dsl_parity.py fails if this
port and NVIDIA's code ever disagree.

  space-separated constraints are ORed, comma-separated constraints are ANDed
  (NVIDIA container-toolkit docs; dsl_evaluate confirms it)

That is why an image whose first term reads cuda>=13.0 can still run on driver
550: the later brand=tesla,driver>=550,driver<551 term is an OR branch, put
there by NVIDIA's base image to declare the driver branches its bundled
cuda-compat package supports. Reading those terms as AND-noise is the difference
between "INCOMPATIBLE" and "COMPATIBLE via forward compatibility", so verdicts
name which term carried them.

Verdicts, per image per target class per platform:

  COMPATIBLE      + basis: native CUDA match, or a forward-compat branch term
  INCOMPATIBLE    the container is refused at start; the message an operator
                  would see in the kubelet log is quoted verbatim
  CANNOT-VERIFY   a fact is missing, or the image declares no CUDA metadata.
                  Never a silent pass.

Facts are three-valued: a missing brand or compute capability makes the terms
that need it UNDECIDED, never assumed-true. A verdict is only issued when it
holds for every value the missing fact could take.

Usage:
  cuda-compat.py IMAGE [IMAGE ...] --target 550.144.03/7.5/amd64/Tesla [--json]
  cuda-compat.py IMAGE --driver 550 --cc 7.5          # single-target shorthand
  cuda-compat.py IMAGE --from-node ctx/node           # read the facts off a node

Target syntax: [LABEL=]DRIVER[/CC[/PLATFORM-ARCH[/BRAND[,BRAND...]]]]
  DRIVER         full version (550.144.03) when known — a bare branch (550)
                 cannot decide terms that compare against a finer version, and
                 says so instead of guessing
  CC             GPU compute capability, e.g. 7.5 — NVIDIA's "arch" property
  PLATFORM-ARCH  which image variant runs here (default amd64). Other variants
                 are reported but never vote: an arm64 child cannot run on an
                 amd64 node.
  BRAND          NVML brand(s) the GPU may report, e.g. Tesla,Nvidia. Datacenter
                 SKUs report different values across driver branches, so a set is
                 allowed; the verdict must hold for all of them.

Exit codes: 0 compatible, 1 incompatible, 2 cannot-verify — ALWAYS, so the
signal is never lost. Consumers choose their own strictness (the composite
action's strict-unknown input decides whether exit 2 fails the step).

Assurance tier: static analysis of image config + the runtime's own requirement
logic. It says "the driver check will/will not refuse this container", not
"boots". It cannot see whether the bundled compat libraries are intact, and a
runtime configured for CDI, or an image setting NVIDIA_DISABLE_REQUIRE, skips
the requirement check altogether — both are reported when detected.

Stdlib only, anonymous registry auth only. Registry credentials belong in the
action wrapper, never here (YP6M-3480) — this file must stay runnable by a
customer with nothing but python3.
"""
import argparse, json, re, subprocess, sys, urllib.error, urllib.parse, urllib.request

SCHEMA = "cuda-compat/v1"
ASSURANCE = ("static analysis of image config against libnvidia-container's own requirement "
             "logic — says 'the driver check will/will not refuse this container', not 'boots'")
DEFAULT_ARCH = "amd64"

# Driver branch -> the CUDA version that branch's driver reports, which is what a
# cuda>=X.Y constraint is compared against (nvc_driver_info.cuda_version).
# Fail-honest: an unknown branch is CANNOT-VERIFY, never interpolated.
DRIVER_MAX_CUDA = {
    "470": "11.4", "510": "11.6", "515": "11.7", "520": "11.8", "525": "12.0",
    "530": "12.1", "535": "12.2", "545": "12.3", "550": "12.4", "555": "12.5",
    "560": "12.6", "565": "12.7", "570": "12.8", "575": "12.9", "580": "13.0",
}

# Every string nvmlDeviceGetBrand can produce, verbatim from libnvidia-container
# src/driver.c (compared case-insensitively). Image requirement strings enumerate
# only the datacenter/virtualization subset, which is exactly why a consumer card
# fails a constraint a Tesla satisfies.
NVML_BRANDS = ("Quadro", "Tesla", "NVS", "GRID", "GeForce", "TITAN", "VApps", "VPC", "VCS",
               "VWS", "CloudGaming", "QuadroRTX", "NvidiaRTX", "Nvidia", "GeForceRTX",
               "TitanRTX", "Unknown")

# Node labels carrying the driver version, most trustworthy first. The GFD labels
# are observed off the running driver; the p6m.dev one is declared by
# karpenter-provisioners. A disagreement is a fact conflict, not a tiebreak.
GFD_DRIVER_LABELS = ("nvidia.com/cuda.driver-version.full", "nvidia.com/cuda.driver.major",
                     "nvidia.com/cuda.driver-version.major")
DECLARED_DRIVER_LABEL = "p6m.dev/cuda.driver-version.major"

MEDIA_INDEX = ("application/vnd.oci.image.index.v1+json",
               "application/vnd.docker.distribution.manifest.list.v2+json")
MEDIA_MANIFEST = ("application/vnd.oci.image.manifest.v1+json",
                  "application/vnd.docker.distribution.manifest.v2+json")
ACCEPT = ", ".join(MEDIA_INDEX + MEDIA_MANIFEST)

LABELS = {0: "COMPATIBLE", 1: "INCOMPATIBLE", 2: "CANNOT-VERIFY"}

# Exit codes are a stable interface (0/1/2), NOT a severity order: 2 is bigger
# than 1 but "could not check" is less severe than "will be refused". Reducing a
# set of verdicts with max() over the exit code would let one unverifiable image
# mask a definitely-refused one and, since exit 2 is a warning by default, let
# the gate go green over a container the runtime will reject. Rank explicitly.
SEVERITY = {0: 0, 2: 1, 1: 2}


def worse(a, b):
    """The more serious of two verdict codes. Never let CANNOT-VERIFY win over INCOMPATIBLE."""
    return a if SEVERITY[a] >= SEVERITY[b] else b


def worst(codes, default=2):
    codes = list(codes)
    return max(codes, key=lambda c: SEVERITY[c]) if codes else default

# Requirement-expression outcomes
SATISFIED, UNSATISFIED, UNDECIDED, MALFORMED = "SATISFIED", "UNSATISFIED", "UNDECIDED", "MALFORMED"


class Refused(Exception):
    """A fact is missing or self-contradictory: refuse, never guess."""


# --------------------------------------------------------------------------
# the DSL — a port of libnvidia-container src/cli/dsl.c
# --------------------------------------------------------------------------

# C: static const struct operator operators[] — matched by the full run of
# operator characters, so "<=" can never be read as "<".
OPERATORS = ("=", "!=", "<", "<=", ">", ">=")
RULES = ("cuda", "driver", "arch", "brand")  # src/cli/configure.c rules[]


def _numeric(s):
    """C: strspn(v, "0123456789.") != strlen(v) -> invalid."""
    return all(ch.isdigit() or ch == "." for ch in s)


def dsl_compare_version(v1, op, v2):
    """Port of dsl_compare_version. Returns True/False, or None for 'invalid'.

    Component-wise numeric compare, then a tail rule: after the shared
    components, whichever side still has a non-zero remainder is the larger.
    Leading zeros are ordinary digits here (550.144.03 == 550.144.3), unlike the
    semver parser the Go implementation uses.
    """
    if not _numeric(v1) or not _numeric(v2):
        return None
    i, j = 0, 0
    while i < len(v1) and j < len(v2):
        mi = re.match(r"\d+", v1[i:])
        mj = re.match(r"\d+", v2[j:])
        if not mi or not mj:      # C: v1 == ptr1 -> no digits consumed -> invalid
            return None
        n1, n2 = int(mi.group()), int(mj.group())
        if n1 != n2:
            if op == "=":
                return False
            if op == "!=":
                return True
            if op in ("<", "<="):
                return n1 < n2
            if op in (">", ">="):
                return n1 > n2
        i += mi.end()
        j += mj.end()
        while i < len(v1) and v1[i] == ".":
            i += 1
        while j < len(v2) and v2[j] == ".":
            j += 1
    # C: v1 += strspn(v1, ".0") — a tail of only dots and zeros counts as absent
    while i < len(v1) and v1[i] in ".0":
        i += 1
    while j < len(v2) and v2[j] in ".0":
        j += 1
    e1, e2 = i >= len(v1), j >= len(v2)
    if op == "!=":
        return not (e1 and e2)
    if op in ("=", "<=", ">="):
        if e1 and e2:
            return True
        if op == "=":
            return False
    if op in ("<", "<="):
        return e1 and not e2
    if op in (">", ">="):
        return not e1 and e2
    return None


def dsl_compare_string(s1, op, s2):
    """Port of dsl_compare_string: only = and != are defined; anything else is invalid."""
    if op == "=":
        return s1.lower() == s2.lower()
    if op == "!=":
        return s1.lower() != s2.lower()
    return None


def parse_factor(factor):
    """C: evaluate_rule's parse step. -> (name, op, value) or None if malformed."""
    m = re.search(r"[<>=!]+", factor)
    if not m or m.start() == 0:      # C: strcspn(...) == 0 -> invalid
        return None
    name, op, value = factor[:m.start()], m.group(), factor[m.end():]
    if op not in OPERATORS or value == "":
        return None
    return name, op, value


def eval_factor(factor, facts):
    """-> (True | False | None-for-undecided, detail, key) or raises on malformed."""
    parsed = parse_factor(factor)
    if parsed is None:
        raise Refused(f"malformed constraint '{factor}'")
    name, op, value = parsed
    key = name.lower()
    if key not in RULES:
        # C: evaluate_rule falls through its rule table and returns -1, which
        # dsl_evaluate turns into "invalid expression" — the container is refused.
        raise Refused(f"unknown property '{name}' (libnvidia-container knows only "
                      f"{', '.join(RULES)}; it refuses the container with 'invalid expression')")
    have = facts.get(key)
    if have is None:
        return None, f"{factor} -> undecided (no {key} fact)", key
    if key == "brand":
        got = dsl_compare_string(have, op, value)
    else:
        # A branch-only driver ("550") cannot settle a comparison against a finer
        # version ("550.54.14") — the missing components are unknown, not zero.
        if key == "driver" and "." not in have and "." in value:
            return None, (f"{factor} -> undecided (target declares driver branch '{have}' only; "
                          f"needs the full version to compare against '{value}')"), key
        got = dsl_compare_version(have, op, value)
    if got is None:
        raise Refused(f"invalid comparison '{factor}' against {key}={have}")
    return got, f"{factor} -> {'ok' if got else 'FAIL'} (have {key} {have})", key


def eval_expression(expr, facts):
    """Port of dsl_evaluate, three-valued.

    Space-separated terms are ORed and evaluated in order; C stops at the first
    term whose comma-separated factors all pass. Undecided factors are the one
    deviation: C has no such state, so where C would have stopped early we keep
    looking, and only report a verdict that holds however the unknown resolves.
    """
    terms = [t for t in expr.split(" ") if t]   # C strsep(&ptr, " "), empties skipped
    undecided = []
    carried = True  # C's `ret`: initialised true, written only by evaluate_rule
    for idx, term in enumerate(terms):
        factors = [f for f in term.split(",") if f]
        if not factors:
            # A term of nothing but separators (", " or ",,"). C's inner strsep
            # loop skips every empty token, ends with and_expr == NULL, and that
            # is the same condition as "all factors passed" — so it BREAKS the
            # OR scan while carrying the preceding term's result. The term
            # decides nothing itself and hides every term after it.
            if carried is True:
                return {"status": SATISFIED, "term": term, "term_index": idx, "keys": [],
                        "detail": "separator-only term: the scan ends here carrying the "
                                  "preceding result, which was still the initial true"}
            break
        state, details, keys = True, [], []
        for factor in factors:
            try:
                got, detail, key = eval_factor(factor, facts)
            except Refused as e:
                if state is None:
                    # C might never have reached this factor: an earlier undecided
                    # factor could have ended the term first. Refuse to guess.
                    details.append(f"{factor} -> unreachable-or-invalid ({e})")
                    state = None
                    break
                raise
            details.append(detail)
            keys.append(key)
            if got is False:
                state = False
                break            # C: if (!ret) break — rest of the term is never evaluated
            if got is None:
                state = None
        if state is True:
            return {"status": SATISFIED, "term": term, "term_index": idx,
                    "keys": sorted(set(keys)), "detail": "; ".join(details)}
        if state is None:
            undecided.append({"term": term, "detail": "; ".join(details)})
        carried = state
    if undecided:
        return {"status": UNDECIDED, "undecided": undecided,
                "detail": "; ".join(u["detail"] for u in undecided[:3])}
    # C reports only the FIRST space-separated term in its error, whichever term
    # actually failed. Quote it as-is: it is the string that lands in the log.
    first = terms[0] if terms else expr
    msg = f"unsatisfied condition: {first}"
    if first.startswith("cuda>="):
        msg += ", please update your driver to a newer version, or use an earlier cuda container"
    return {"status": UNSATISFIED, "message": msg, "detail": f"no term of {len(terms)} satisfied"}


# --------------------------------------------------------------------------
# requirements as the runtime collects them
# --------------------------------------------------------------------------

def collect_requirements(env):
    """Mirror of nvidia-container-toolkit CUDA.GetRequirements().

    Every NVIDIA_REQUIRE_* var (except JETPACK) is passed to nvidia-container-cli
    as its own --require and they are ANDed. A "legacy" image — CUDA_VERSION set
    and no NVIDIA_REQUIRE_CUDA — has cuda>=<major.minor> synthesized for it, so
    CUDA_VERSION is enforced in exactly that case and inert otherwise.
    """
    if str(env.get("NVIDIA_DISABLE_REQUIRE", "")).lower() in ("1", "true", "t", "yes"):
        return [], "NVIDIA_DISABLE_REQUIRE is set — the runtime skips every requirement check"
    reqs = [(k, v) for k, v in sorted(env.items())
            if k.startswith("NVIDIA_REQUIRE_") and not k.startswith("NVIDIA_REQUIRE_JETPACK") and v]
    # IsLegacy() reads ONLY NVIDIA_REQUIRE_CUDA, and GetRequirements APPENDS the
    # synthesized constraint. Gating on "no NVIDIA_REQUIRE_* at all", or replacing
    # rather than appending, drops a conjunct the runtime enforces — and dropping
    # a conjunct can only ever make this tool more permissive than the runtime.
    if not env.get("NVIDIA_REQUIRE_CUDA") and env.get("CUDA_VERSION"):
        m = re.match(r"v?(\d+)\.(\d+)", env["CUDA_VERSION"])
        if m:
            reqs.append(("CUDA_VERSION (legacy image — the runtime synthesizes this requirement)",
                         f"cuda>={m.group(1)}.{m.group(2)}"))
    return reqs, None


def evaluate_requirements(env, target):
    """-> (status, findings, basis). Unanimous across every brand the GPU may report."""
    reqs, skipped = collect_requirements(env)
    if skipped:
        return UNDECIDED, [("requirement check", None, skipped +
                            " — the container starts, but nothing verified its CUDA fitness")], None
    if not reqs:
        return UNDECIDED, [("CUDA metadata", None,
                            "image declares neither NVIDIA_REQUIRE_* nor CUDA_VERSION — cannot "
                            "verify; consider a p6m.dev/cuda-requires annotation")], None

    brands = target.brands or list(NVML_BRANDS)
    per_brand = {}
    for brand in brands:
        facts = {"cuda": target.max_cuda, "driver": target.driver,
                 "arch": target.cc, "brand": brand}
        results = []
        for name, expr in reqs:
            try:
                results.append((name, expr, eval_expression(expr, facts)))
            except Refused as e:
                results.append((name, expr, {"status": MALFORMED, "detail": str(e)}))
        per_brand[brand] = results

    statuses = {b: combine(r) for b, r in per_brand.items()}
    unanimous = set(statuses.values())
    probe = brands[0]
    findings, basis = [], None
    for name, expr, res in per_brand[probe]:
        if res["status"] == SATISFIED:
            basis = ("native CUDA-version match" if res["keys"] == ["cuda"] else
                     f"driver-branch allowance '{res['term']}' — CUDA forward compatibility: the "
                     f"image ships a cuda-compat runtime declaring support for this branch "
                     f"(NVIDIA supports this on datacenter GPUs only)")
            findings.append((f"{name} (enforced at container start)", True,
                             f"satisfied by term #{res['term_index'] + 1} '{res['term']}': {res['detail']}"))
        elif res["status"] == UNSATISFIED:
            findings.append((f"{name} (enforced at container start)", False,
                             f"container refused at start — \"{res['message']}\""))
        elif res["status"] == MALFORMED:
            findings.append((f"{name}", None, res["detail"]))
        else:
            findings.append((f"{name} (enforced at container start)", None,
                             f"undecided: {res['detail']}"))

    if len(unanimous) > 1:
        deciding = sorted(f"{b}={s}" for b, s in statuses.items())
        return UNDECIDED, findings + [
            ("GPU brand", None, "verdict depends on which brand the GPU reports "
                                f"({', '.join(deciding[:6])}{'...' if len(deciding) > 6 else ''}) — "
                                "declare the brand on the target to decide")], basis
    return unanimous.pop(), findings, basis


def combine(results):
    """AND across the image's separate NVIDIA_REQUIRE_* variables."""
    order = [r["status"] for _, _, r in results]
    for bad in (MALFORMED, UNSATISFIED, UNDECIDED):
        if bad in order:
            return bad
    return SATISFIED


# --------------------------------------------------------------------------
# targets
# --------------------------------------------------------------------------

class Target:
    def __init__(self, driver, cc=None, arch=DEFAULT_ARCH, brands=None, label=None, provenance=None):
        self.driver, self.cc, self.arch = driver, cc, arch
        self.brands = list(brands or [])
        self.label = label or "/".join([driver] + ([cc] if cc else []) +
                                       ([arch] if arch != DEFAULT_ARCH else []))
        self.provenance = provenance
        self.branch = driver.split(".")[0]
        self.max_cuda = DRIVER_MAX_CUDA.get(self.branch)

    def as_dict(self):
        return {"label": self.label, "driver": self.driver, "branch": self.branch, "cc": self.cc,
                "arch": self.arch, "brands": self.brands, "max_cuda": self.max_cuda,
                "provenance": self.provenance}


def parse_target(spec):
    """[LABEL=]DRIVER[/CC[/ARCH[/BRAND,BRAND]]] — empty fields allowed as 550//arm64."""
    label = None
    if "=" in spec:
        label, spec = spec.split("=", 1)
    parts = [p.strip() for p in spec.split("/")]
    if not parts[0]:
        raise Refused(f"target '{spec}' declares no driver version")
    get = lambda i: parts[i] if len(parts) > i and parts[i] else None
    brands = [b.strip() for b in (get(3) or "").split(",") if b.strip()]
    return Target(parts[0], get(1), (get(2) or DEFAULT_ARCH).replace("linux/", ""), brands, label)


def target_from_node_labels(labels, node_name="node"):
    """Pure: node labels -> Target. Refuses on missing or contradictory facts."""
    observed = next(((k, labels[k]) for k in GFD_DRIVER_LABELS if labels.get(k)), None)
    declared = labels.get(DECLARED_DRIVER_LABEL)
    if observed and declared and observed[1].split(".")[0] != declared:
        raise Refused(
            f"node {node_name} contradicts itself: observed {observed[0]}={observed[1]} "
            f"but declared {DECLARED_DRIVER_LABEL}={declared}. A node whose own facts "
            f"disagree cannot ground a verdict — fix the declaration (the drift audit "
            f"owns this class of finding) or pass --target explicitly.")
    source = observed or ((DECLARED_DRIVER_LABEL, declared) if declared else None)
    if not source:
        raise Refused(
            f"node {node_name} declares no driver fact "
            f"({', '.join(GFD_DRIVER_LABELS + (DECLARED_DRIVER_LABEL,))}) — "
            f"cannot verify; pass --target explicitly if you know the branch.")
    major, minor = labels.get("nvidia.com/gpu.compute.major"), labels.get("nvidia.com/gpu.compute.minor")
    cc = f"{major}.{minor}" if major and minor else None
    arch = labels.get("kubernetes.io/arch") or DEFAULT_ARCH
    prov = f"{source[0]}={source[1]}" + (f", nvidia.com/gpu.compute.*={cc}" if cc else
                                         ", no GFD compute-capability labels (arch axis undecided)")
    return Target(source[1], cc, arch, brands=None, label=node_name, provenance=prov)


def node_labels(spec):
    """--from-node [context/]node — the only step that touches a cluster."""
    context, _, name = spec.rpartition("/")
    cmd = ["kubectl"] + (["--context", context] if context else []) + \
          ["get", "node", name, "-o", "json"]
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, timeout=60, check=True).stdout
    except (OSError, subprocess.SubprocessError) as e:
        stderr = getattr(e, "stderr", "") or str(e)
        raise Refused(f"could not read node '{spec}': {stderr.strip()}")
    return json.loads(out).get("metadata", {}).get("labels", {}), name


# --------------------------------------------------------------------------
# registry
# --------------------------------------------------------------------------

def parse_ref(ref):
    # [registry/]repo[:tag][@digest]
    digest = None
    if "@" in ref:
        ref, digest = ref.split("@", 1)
    tag = "latest"
    if ":" in ref.rsplit("/", 1)[-1]:
        ref, tag = ref.rsplit(":", 1)
    parts = ref.split("/")
    if "." in parts[0] or ":" in parts[0] or parts[0] == "localhost":
        registry, repo = parts[0], "/".join(parts[1:])
    else:
        registry, repo = "registry-1.docker.io", ref if "/" in ref else f"library/{ref}"
    return registry, repo, (digest or tag)


class Registry:
    def __init__(self, registry, repo):
        self.base = f"https://{registry}/v2/{repo}"
        self.repo = repo
        self.token = None

    def _get(self, url, accept, _retried=False):
        req = urllib.request.Request(url, headers={"Accept": accept})
        if self.token:
            req.add_header("Authorization", f"Bearer {self.token}")
        try:
            resp = urllib.request.urlopen(req, timeout=30)
            return resp.read(), resp.headers  # case-insensitive Message, not a dict
        except urllib.error.HTTPError as e:
            if e.code != 401 or self.token:
                raise
            if _retried:
                raise Refused(f"{url}: registry kept answering 401 after a token exchange")
            challenge = e.headers.get("WWW-Authenticate", "")
            m = dict(re.findall(r'(\w+)="([^"]*)"', challenge))
            if "realm" not in m:
                raise
            # The realm comes from the registry, i.e. from whoever we are asking
            # about. It must not be able to send us somewhere else in plaintext.
            realm = urllib.parse.urlsplit(m["realm"])
            if realm.scheme != "https" or not realm.hostname:
                raise Refused(f"registry offered a non-https auth realm: {m['realm']}")
            q = {"service": m.get("service", ""), "scope": m.get("scope", f"repository:{self.repo}:pull")}
            tok = json.loads(urllib.request.urlopen(
                f"{m['realm']}?{urllib.parse.urlencode(q)}", timeout=30).read())
            self.token = tok.get("token") or tok.get("access_token")
            if not self.token:
                raise Refused("token endpoint returned neither token nor access_token")
            return self._get(url, accept, _retried=True)

    def manifest(self, ref):
        body, headers = self._get(f"{self.base}/manifests/{ref}", ACCEPT)
        digest = headers.get("Docker-Content-Digest")
        # Registry-controlled text that we print, and that the action forwards
        # into $GITHUB_OUTPUT and issue bodies. Accept only the shape it claims.
        if digest and not re.fullmatch(r"[a-z0-9]+:[a-f0-9]{32,128}", digest):
            digest = None
        return json.loads(body), digest

    def blob(self, digest):
        body, _ = self._get(f"{self.base}/blobs/{digest}", "*/*")
        return json.loads(body)


def env_map(config):
    out = {}
    for e in (config.get("config") or {}).get("Env") or []:
        k, _, v = e.partition("=")
        out[k] = v
    return out


def fetch_platforms(image):
    """-> (index_digest, [{platform, arch, digest, env}]) — every linux child, once."""
    registry, repo, ref = parse_ref(image)
    reg = Registry(registry, repo)
    top, top_digest = reg.manifest(ref)
    resolved = top_digest or (ref if ref.startswith("sha256:") else None)

    out = []
    if top.get("mediaType") in MEDIA_INDEX or "manifests" in top:
        for m in top["manifests"]:
            p = m.get("platform") or {}
            # attestation manifests ride in the index as unknown/unknown children
            if p.get("os") != "linux" or m.get("annotations", {}).get("vnd.docker.reference.type"):
                continue
            man, _ = reg.manifest(m["digest"])
            out.append({"platform": f"linux/{p.get('architecture')}",
                        "arch": p.get("architecture"),
                        "digest": m["digest"],
                        "env": env_map(reg.blob(man["config"]["digest"]))})
    else:
        # No index: the config blob is the only place the arch is stated.
        cfg = reg.blob(top["config"]["digest"])
        arch = cfg.get("architecture")
        out.append({"platform": f"{cfg.get('os', 'linux')}/{arch or 'unknown-arch'}",
                    "arch": arch, "digest": resolved, "env": env_map(cfg)})
    if not out:
        raise Refused(f"{image}: index declares no linux platform manifests")
    return resolved, out


# --------------------------------------------------------------------------
# verdicts
# --------------------------------------------------------------------------

def vtuple(s):
    return tuple(int(x) for x in re.findall(r"\d+", s)[:3]) or (0,)


def split_arch_entry(entry):
    """'12.0a+PTX' -> ('12.0', 'a', True).

    CUDA 12.8 added arch-accelerated targets (sm_100a, sm_120a) and 12.9 added
    family-specific ones (sm_100f). The suffix marks EXTRA instructions compiled
    in for that exact architecture — Blackwell's tcgen05 tensor-core ops and the
    NVFP4/MXFP6 datatypes among them — so '12.0a' covers compute capability 12.0
    and then some. Reading the suffix as part of the number makes a correctly
    built Blackwell image look uncompiled.
    """
    ptx = entry.endswith("+PTX")
    base = entry[:-4] if ptx else entry
    suffix = ""
    if base and base[-1] in ("a", "f"):
        base, suffix = base[:-1], base[-1]
    return base, suffix, ptx


def check_arch(arch_list, cc):
    entries = [e for e in re.split(r"[;,\s]+", arch_list.strip()) if e]
    parsed = [split_arch_entry(e) for e in entries]

    for base, suffix, _ in parsed:
        if base == cc:
            extra = {"a": " (arch-accelerated target — the Blackwell-class instructions "
                          "and datatypes are compiled in)",
                     "f": " (family-specific target)"}.get(suffix, "")
            return True, f"compute capability {cc} in TORCH_CUDA_ARCH_LIST ({arch_list}){extra}"

    # PTX is JIT-forward-compatible, but ONLY to generic instructions: arch-
    # accelerated ops cannot be JIT'd from generic PTX at all. On Blackwell that
    # makes "works via PTX" mean "runs without the hardware you paid for".
    ptx = [base for base, _, is_ptx in parsed if is_ptx]
    if ptx and any(vtuple(p) <= vtuple(cc) for p in ptx):
        return True, (f"{cc} not compiled, but PTX from {max(ptx, key=vtuple)} JIT-forward-compatible "
                      f"({arch_list}) — first launch is slow, not guaranteed for all kernels, and no "
                      f"arch-accelerated instruction can be reached this way")
    return False, f"compute capability {cc} not in TORCH_CUDA_ARCH_LIST ({arch_list}), no applicable +PTX"


def verdict_for_platform(env, target):
    """-> (worst, findings, basis). 0 compatible, 1 incompatible, 2 cannot-verify."""
    status, findings, basis = evaluate_requirements(env, target)
    worst = {SATISFIED: 0, UNSATISFIED: 1, UNDECIDED: 2, MALFORMED: 1}[status]
    if status == MALFORMED:
        findings.append(("requirement expression", False,
                         "libnvidia-container refuses a malformed expression outright — "
                         "the container will not start"))

    # Not enforced at container start: this axis decides whether compiled kernels
    # exist once it is running (a YP6M-3505-class failure), so it is reported
    # separately and never confused with the driver check.
    arch = env.get("TORCH_CUDA_ARCH_LIST")
    if target.cc:
        if arch:
            ok, detail = check_arch(arch, target.cc)
            findings.append(("TORCH_CUDA_ARCH_LIST vs cc (not enforced at start; decides kernel fit)",
                             ok, detail))
            if not ok:
                # A settled arch mismatch is a definite refusal; it must not be
                # reported as merely unverified just because the driver axis was.
                worst = worse(worst, 1)
        else:
            findings.append(("TORCH_CUDA_ARCH_LIST", None,
                             f"kernel fit for compute capability {target.cc} unverified: the "
                             f"image declares no TORCH_CUDA_ARCH_LIST"))
    return worst, findings, basis


def evaluate(image, platforms, index_digest, target):
    """One image against one target -> a result dict (JSON-shaped)."""
    if not target.max_cuda:
        return {"image": image, "digest": index_digest, "target": target.as_dict(),
                "verdict": LABELS[2], "exit": 2, "platforms": [],
                "refusal": f"driver branch '{target.branch}' is not in the known table "
                           f"({', '.join(sorted(DRIVER_MAX_CUDA))}) — add it deliberately, never guess"}

    entries, worst, targeted_any, basis = [], 0, False, None
    for p in platforms:
        targeted = p["arch"] is None or p["arch"] == target.arch
        w, findings, b = verdict_for_platform(p["env"], target)
        entries.append({
            "platform": p["platform"], "digest": p["digest"], "targeted": targeted,
            "verdict": LABELS[w], "basis": b,
            "findings": [{"check": n, "status": {True: "ok", False: "fail", None: "unknown"}[o],
                          "detail": d} for n, o, d in findings]})
        if targeted:
            targeted_any = True
            worst = worse(worst, w)
            basis = basis or b

    result = {"image": image, "digest": index_digest, "target": target.as_dict(),
              "platforms": entries, "basis": basis}
    if not targeted_any:
        result.update({"verdict": LABELS[2], "exit": 2,
                       "refusal": f"image publishes no linux/{target.arch} variant "
                                  f"(has: {', '.join(p['platform'] for p in platforms)}) — "
                                  f"cannot verify what would run on this target"})
    else:
        result.update({"verdict": LABELS[worst], "exit": worst})
    return result


# --------------------------------------------------------------------------
# output
# --------------------------------------------------------------------------

MARK = {"ok": "ok  ", "fail": "FAIL", "unknown": "?   "}


def print_text(report):
    for r in report["results"]:
        t = r["target"]
        print(f"\nimage:  {r['image']}" + (f"\n        {r['digest']}" if r["digest"] else ""))
        prov = f"  [{t['provenance']}]" if t.get("provenance") else ""
        print(f"target: {t['label']} — driver {t['driver']}"
              + (f" (reports CUDA {t['max_cuda']})" if t["max_cuda"] else " (UNKNOWN BRANCH)")
              + (f", compute capability {t['cc']}" if t["cc"] else "")
              + (f", brand {'|'.join(t['brands'])}" if t["brands"] else "")
              + f", linux/{t['arch']}{prov}")
        if r.get("refusal"):
            print(f"  CANNOT-VERIFY: {r['refusal']}")
        for p in r["platforms"]:
            scope = "" if p["targeted"] else "  (not targeted — informational)"
            print(f"\n  {p['platform']}: {p['verdict']}{scope}")
            for f in p["findings"]:
                print(f"    [{MARK[f['status']]}] {f['check']}: {f['detail']}")
        print(f"\n  => {r['image']} on {t['label']}: {r['verdict']}"
              + (f"\n     basis: {r['basis']}" if r.get("basis") else ""))
    print(f"\nverdict: {report['verdict']}\nassurance: {report['assurance']}")


def main():
    ap = argparse.ArgumentParser(
        description="Static CUDA compatibility verdict for container images against driver/GPU targets.")
    ap.add_argument("images", nargs="+", metavar="IMAGE")
    ap.add_argument("--target", action="append", default=[],
                    metavar="[LABEL=]DRIVER[/CC[/ARCH[/BRAND]]]",
                    help="repeatable target class, e.g. playground-t4=550.144.03/7.5/amd64/Tesla")
    ap.add_argument("--driver", help="single-target shorthand: driver version or branch, e.g. 550")
    ap.add_argument("--cc", help="single-target shorthand: compute capability, e.g. 7.5")
    ap.add_argument("--brand", help="single-target shorthand: NVML brand(s), e.g. Tesla,Nvidia")
    ap.add_argument("--arch", default=DEFAULT_ARCH, help=f"image arch for --driver (default {DEFAULT_ARCH})")
    ap.add_argument("--from-node", metavar="[CONTEXT/]NODE",
                    help="derive a target from a live node's labels (needs kubectl)")
    ap.add_argument("--json", action="store_true", help="machine-readable report on stdout")
    args = ap.parse_args()

    targets = []
    try:
        targets += [parse_target(s) for s in args.target]
        if args.driver:
            targets.append(Target(args.driver, args.cc, args.arch.replace("linux/", ""),
                                  [b.strip() for b in (args.brand or "").split(",") if b.strip()]))
        elif args.cc or args.brand:
            raise Refused("--cc/--brand without --driver: not a target on their own")
        if args.from_node:
            labels, name = node_labels(args.from_node)
            targets.append(target_from_node_labels(labels, name))
    except Refused as e:
        print(f"CANNOT-VERIFY: {e}", file=sys.stderr)
        sys.exit(2)

    if not targets:
        ap.error("no target given: use --target, --driver, or --from-node")

    results = []
    for image in args.images:
        try:
            index_digest, platforms = fetch_platforms(image)
        except (Refused, urllib.error.URLError, urllib.error.HTTPError,
                OSError, KeyError, ValueError) as e:
            for t in targets:
                results.append({"image": image, "digest": None, "target": t.as_dict(),
                                "verdict": LABELS[2], "exit": 2, "platforms": [],
                                "refusal": f"could not read image metadata: {e}"})
            continue
        results.extend(evaluate(image, platforms, index_digest, t) for t in targets)

    overall = worst((r["exit"] for r in results), default=2)
    report = {"schema": SCHEMA, "assurance": ASSURANCE, "verdict": LABELS[overall],
              "exit": overall, "results": results}
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print_text(report)
    sys.exit(overall)


if __name__ == "__main__":
    main()
