on:
  workflow_call:
    secrets:
      SSH_KEY:
        required: true
      SSO_URL:
        required: true
      ARTIFACTORY_DOCKERCONFIG:
        required: true
      ARGOCD_CERTIFICATE:
        required: true
      GRAFANA_CLIENT_ID:
        required: true
      GRAFANA_CLIENT_SECRET:
        required: true

name: Destroy Infrastructure

permissions:
  id-token: write
  contents: read

env:
  TERRAFORM_VERSION: 1.2.9
  AWS_DEFAULT_REGION: ${{ vars.AWS_REGION}}
  AWS_REGION: ${{ vars.AWS_REGION}}
  AWS_DEFAULT_OUTPUT: json
  TF_VAR_region: ${{ vars.AWS_REGION}}
  TF_VAR_jv: ${{ vars.TF_VAR_JV}}
  TF_VAR_jv_short_name: ${{ vars.TF_VAR_JV }}
  TF_VAR_jv_project: ${{ vars.TF_VAR_JV_PROJECT}}
  TF_VAR_jv_name: ${{ vars.TF_VAR_JV_NAME }}
  AWS_MATRIX: ${{ vars.AWS_MATRIX}}
  TF_VAR_state_bucket: ${{ vars.TF_VAR_STATE_BUCKET }}
  TF_VAR_grafana_client_id: ${{ secrets.GRAFANA_CLIENT_ID }}
  TF_VAR_grafana_client_secret: ${{ secrets.GRAFANA_CLIENT_SECRET }}
  TF_VAR_cluster_name: ${{ vars.CLUSTER_NAME }}

jobs:
  load_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - id: set-matrix
        name: matrix
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "matrix<<$EOF" >> $GITHUB_OUTPUT
          echo "{    \"include\": ${AWS_MATRIX} }"  >> $GITHUB_OUTPUT
          echo >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
  jv:
    environment: ${{ matrix.env }}
    needs: load_matrix
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix: ${{fromJson(needs.load_matrix.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS credentials for shared services account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GithubActionsInfraRole
          aws-region: us-west-2

      - name: Run Terraform init
        id: init
        working-directory: terraform
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.SSH_KEY }}'
          terraform init -input=false --backend-config="bucket=${TF_VAR_state_bucket}" --backend-config="key=${TF_VAR_jv}/terraform.tfstate" --backend-config="region=${TF_VAR_region}"
          terraform workspace new "${{ matrix.env }}" || true
          terraform workspace select "${{ matrix.env }}"
        env:
          TF_VAR_account_id: ${{ matrix.id }}
          TF_VAR_env: ${{ matrix.env }}

      - name: Terraform Validate
        id: validate
        working-directory: terraform
        run: terraform validate -no-color
        env:
          TF_VAR_account_id: ${{ matrix.id }}
          TF_VAR_env: ${{ matrix.env }}
          TF_WORKSPACE: ${{ matrix.env }}
      - name: Terraform Destroy
        id: destroy
        working-directory: terraform
        run: |
          echo env jv $TF_VAR_jv
          echo env name $TF_VAR_jv_name
          echo env project $TF_VAR_jv_project
          echo var project ${{ vars.TF_VAR_JV_PROJECT }}
          echo var name ${{ vars.TF_VAR_JV_NAME }} 
          terraform workspace list
          terraform destroy -auto-approve -input=false -refresh=false
        env:
          TF_VAR_github_ssh_key: ${{ secrets.SSH_KEY }}
          TF_VAR_account_id: ${{ matrix.id }}
          TF_VAR_env: ${{ matrix.env }}
          TF_VAR_jv_name: ${{ vars.TF_VAR_JV_NAME}}
          TF_VAR_jv_project: ${{ vars.TF_VAR_JV_PROJECT }}
          TF_WORKSPACE: ${{ matrix.env }}
          TF_VAR_sso_url: ${{ secrets.SSO_URL }}
          TF_VAR_docker_json_config: ${{ secrets.ARTIFACTORY_DOCKERCONFIG }}
          TF_VAR_argocd_certificate: ${{ secrets.ARGOCD_CERTIFICATE }}
