name: Mirror to ybor-tech

on:
  push:
    branches:
      - main

jobs:
  mirror:
    if: github.repository_owner == 'ybor-platform'
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@v0.7.0
          with:
            REMOTE: git@github.com:ybor-tech/github-actions.git
            GIT_USERNAME: cnuss
            GIT_SSH_PRIVATE_KEY: ${{ secrets.YBOR_TECH_SSH_KEY }}
            GIT_SSH_NO_VERIFY_HOST: true
