name: Build & Deploy (.NET Service)

on:
  workflow_call:
    outputs:
      digest:
        description: "The docker image digest for the built image"
        value: ${{ jobs.build.outputs.digest }}
    secrets:
      ARTIFACTORY_USERNAME:
        description: The username to use to authenticate with the Docker registry.
        required: true
      ARTIFACTORY_IDENTITY_TOKEN:
        description: The password to use to authenticate with the Docker registry.
        required: true

      UPDATE_MANIFEST_TOKEN:
        description: The token to use to push the new image digest to the .platform repo.
        required: true
    inputs:
      MODE:
        description: Release or Debug mode
        type: string
        required: false
        default: release
      DOTNET_VERSION:
        description: .NET version (8.0, 9.0, etc)
        type: string
        required: false
        default: "8.0"
      ARTIFACTORY_HOSTNAME:
        description: The hostname of the Docker registry as you would enter it for the `docker login` command.
        type: string
        required: false
      ARTIFACTORY_REPO:
        description: Artifactory repository name.
        type: string
        required: true
      DOCKER_IMAGE_NAME:
        description: "The namespaced Docker image name."
        type: string
        required: true
      DOCKER_CONTEXT:
        description: The path to the Docker context to build.
        type: string
        default: '.'
        required: false
      DOCKERFILE:
        description: The absolute path to the Dockerfile to build.
        type: string
        default: './Dockerfile'
        required: false

env:
  ARTIFACTORY_HOSTNAME: ${{ inputs.ARTIFACTORY_HOSTNAME || vars.ARTIFACTORY_HOSTNAME }}
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME}}
  ARTIFACTORY_IDENTITY_TOKEN: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}

jobs:
  build:
    name: Build
    outputs:
    #   version: ${{ steps.pkg-version.outputs.VERSION }}
      digest: ${{ steps.docker_build.outputs.digest }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.DOTNET_VERSION }}

      - name: Login to Docker Repository
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ARTIFACTORY_HOSTNAME }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}

      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Build
        run: |
          dotnet restore
          dotnet build -c Release --no-restore 
          dotnet publish -c Release -o ./publish

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal  

      - name: Pack and push nuget packages
        if: github.ref_name == 'main'
        run: |
          dotnet pack -c Release -o ./artifacts
          for package in ./artifacts/*.nupkg; do
            dotnet nuget push "$package" --source "${{ github.repository_owner }}-nuget" --api-key "${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}"
          done

      - name: Docker meta
        if: github.ref_name == 'main'
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.ARTIFACTORY_HOSTNAME }}/${{ inputs.ARTIFACTORY_REPO }}/${{ inputs.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=schedule,pattern=latest
            type=sha

      - name: Docker Build and Push
        if: github.ref_name == 'main'
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.DOCKER_CONTEXT }}
          file: ${{ inputs.DOCKERFILE }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Get TAG version
        if: github.ref_name == 'main'
        id: TAG
        run: |
          version=$(xmlstarlet sel -t -v "//VersionPrefix" Directory.Build.props)
          echo "release_version=$version"
          echo "release_version=$version" >> $GITHUB_OUTPUT
          echo "tag_name=v$version"
          echo "tag_name=v$version" >> $GITHUB_OUTPUT

      - name: Commit & Tag Version
        if: github.ref_name == 'main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a ${{ steps.TAG.outputs.tag_name }} -m "Release ${{ steps.TAG.outputs.value }}"
          git push origin ${{ steps.TAG.outputs.tag_name }}

      - name: Bump release version
        if: github.ref_name == 'main'
        id: increment_version
        run: |
          # Split version into components
          IFS='.' read -ra VERSION_PARTS <<< "${{ steps.TAG.outputs.release_version }}"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}

          # Determine which part to increment based on input
          if [ "${{ github.event.inputs.release_type }}" == "major" ]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [ "${{ github.event.inputs.release_type }}" == "minor" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi

          # Construct the new version
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

          xmlstarlet ed --inplace -u "//VersionPrefix" -v "${NEW_VERSION}" Directory.Build.props
          cat Directory.Build.props  # Print to verify the update

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -am "[skip ci] Bump version ${NEW_VERSION}"
          git push origin main

      - name: Record Summary
        run: |
          echo "### Tag Name" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.TAG.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
          echo "### Docker Image Digest" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.docker_build.outputs.digest }}" >> $GITHUB_STEP_SUMMARY
          echo "### Release Version" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.TAG.outputs.release_version }}" >> $GITHUB_STEP_SUMMARY
      
  trigger-cd:
    name: Trigger CD
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Trigger Update Image Digest
        run: |
          echo ${{ github.ref }}
          echo ${{ needs.build.outputs.digest }}
          echo ${{ vars.PLATFORM_DISPATCH_URL }}
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.UPDATE_MANIFEST_TOKEN }}" \
            ${{ vars.PLATFORM_DISPATCH_URL }} \
            --fail-with-body \
            -d "{\"event_type\": \"update-digest\", \"client_payload\": {\"repository\": \"${GITHUB_REPOSITORY}\", \"directory_name\": \"$(basename ${GITHUB_REPOSITORY})\", \"image_name\": \"${{ inputs.DOCKER_IMAGE_NAME }}\",\"environment_dir\": \"dev\", \"digest\": \"${{ needs.build.outputs.digest }}\"}}"
