name: Deploy Helm Chart

on:
  workflow_call:
    inputs:
      namespace:
        description: 'Corresponds to Artifactory Project or Cloudsmith repo name.'
        required: false
        type: string
        default: ${{ github.repository_owner }}
      deploy:
        description: 'A value indicating whether to push out the Helm chart and bump the version.'
        required: false
        type: boolean
        default: false
      platform-installation-id:
        description: 'The installation ID of the p6m-ybor app for the github org.'
        type: string
        required: false
        default: ${{ vars.PLATFORM_INSTALLATION_ID }}
      ARTIFACTORY_HOSTNAME:
        description: The hostname of the Docker registry as you would enter it for the `docker login` command.
        type: string
        required: false
        default: p6m.jfrog.io
    secrets:
      ARTIFACTORY_USERNAME:
        description: 'Artifactory Username'
        required: true
      ARTIFACTORY_IDENTITY_TOKEN:
        description: 'Artifactory Identity Token'
        required: true

permissions:
  contents: write
  id-token: write

env:
  ARTIFACTORY_HOSTNAME: ${{ inputs.ARTIFACTORY_HOSTNAME || vars.ARTIFACTORY_HOSTNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Artifactory Docker Repository
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ARTIFACTORY_HOSTNAME}}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}

      - name: Helm Package
        run: helm package .

      - name: Get Current Version
        id: current_version
        run: |
          VERSION=$(cat Chart.yaml | grep -e "^version: " | cut -d" " -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Helm Push
        if: ${{ inputs.deploy }}
        run: helm push ${{ github.event.repository.name }}-${{ steps.current_version.outputs.version }}.tgz  oci://${{ env.ARTIFACTORY_HOSTNAME}}/${{ inputs.namespace }}-docker

      - name: Automated Version Bump
        run: |
          pipx install pybump
          pybump bump --file ./Chart.yaml --level patch

      - name: Tag then Commit
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        uses: p6m-actions/p6m-release-action@v2
        env:
          PLATFORM_TOKEN_EXCHANGE_URL: https://auth.p6m.dev/api/github/actions/token-exchange
          PLATFORM_INSTALLATION_ID: ${{ inputs.platform-installation-id }}
        with:
          tags:
            v${{ steps.current_version.outputs.version }}
