name: Deploy Helm Chart

on:
  workflow_call:
    inputs:
      namespace:
        description: 'Corresponds to Artifactory Project or Cloudsmith repo name.'
        required: false
        type: string
        default: ${{ github.repository_owner }}
      deploy:
        description: 'A value indicating whether to push out the Helm chart and bump the version.'
        required: false
        type: boolean
        default: false
      chart_dir:
        description: 'Directory containing the Helm chart.'
        required: false
        type: string
        default: '.'
      bump_app_version:
        description: 'Whether to also bump the appVersion field.'
        required: false
        type: boolean
        default: false
      ARTIFACTORY_HOSTNAME:
        description: The hostname of the Docker registry as you would enter it for the `docker login` command.
        type: string
        required: false
        default: p6m.jfrog.io
    secrets:
      ARTIFACTORY_USERNAME:
        description: 'Artifactory Username'
        required: true
      ARTIFACTORY_IDENTITY_TOKEN:
        description: 'Artifactory Identity Token'
        required: true

permissions:
  contents: write

env:
  ARTIFACTORY_HOSTNAME: ${{ inputs.ARTIFACTORY_HOSTNAME || vars.ARTIFACTORY_HOSTNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Artifactory Docker Repository
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ARTIFACTORY_HOSTNAME}}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}

      - name: Helm Package
        run: helm package .
        working-directory: ${{ inputs.chart_dir }}

      - name: Get Current Version
        id: current_version
        run: |
          VERSION=$(cat Chart.yaml | grep -e "^version: " | cut -d" " -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        working-directory: ${{ inputs.chart_dir }}

      - name: Helm Push
        if: ${{ inputs.deploy }}
        run: helm push ${{ github.event.repository.name }}-${{ steps.current_version.outputs.version }}.tgz  oci://${{ env.ARTIFACTORY_HOSTNAME}}/${{ inputs.namespace }}-docker
        working-directory: ${{ inputs.chart_dir }}

      - name: Automated Version Bump
        run: |
          pipx install pybump
          CMD="pybump bump --file 'Chart.yaml' --level patch"
          if [[ "${{ inputs.bump_app_version }}" == "true" ]]; then
            CMD="$CMD --app-version"
          fi
          eval "$CMD"
        working-directory: ${{ inputs.chart_dir }}

      - name: Commit and Push
        if: ${{ inputs.deploy }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[skip ci] Bump Version"
          git push
