on:
  workflow_call:
    inputs:
      APPLICATION_IMAGE:
        required: true
        type: string
    secrets:
      SUBGRAPH_PULL_TOKEN:
        required: true
      REPOSITORY_PUSH_TOKEN:
        required: true
      ARTIFACTORY_USERNAME:
        required: true
      ARTIFACTORY_IDENTITY_TOKEN:
        required: true
      PIPELINE_TRIGGER_TOKEN:
        required: true

jobs:
  generate_subgraph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Ensure we have the latest code
        run: git pull

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.7.3
        with:
          shared-key: build

      - name: Generate Subgraph
        id: generate_subgraph
        env:
          CARGO_INCREMENTAL: "1"
        run: |
          cargo run --release schema > ${{ github.event.repository.name }}.graphql
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "subgraph<<$EOF" >> $GITHUB_OUTPUT
          echo "$(cat './${{ github.event.repository.name }}.graphql')"  >> $GITHUB_OUTPUT
          echo >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - uses: actions/github-script@v7
        name: Add Pull Request Comment
        if: github.event_name == 'pull_request'
        continue-on-error: true
        with:
          script: |
            const output = `Subgraph Generated by automation
            <details><summary>${{ github.event.repository.name }}.graphql</summary>
            \`\`\`graphql\n
            ${{ steps.generate_subgraph.outputs.subgraph }}
            \`\`\`
            </details>`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Update git branch
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "[skip ci] Update ${{ github.event.repository.name }} subgraph" && git push origin ${{ github.ref_name }}

      - name: Trigger Update Federated Gateway
        if: github.ref == 'refs/heads/main'
        run: |
          echo https://api.github.com/repos/${{ github.repository_owner }}/graphql-federated-gateway/dispatches
          curl -X POST \
              -H "Accept: application/vnd.github.everest-preview+json" \
              -H "Authorization: token ${{ secrets.PIPELINE_TRIGGER_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository_owner }}/graphql-federated-gateway/dispatches \
              -d "{\"event_type\": \"update_subgraph\"}"
