name: Test

on:
  workflow_call:
    inputs:
      REACT_APP_ENV:
        required: false
        type: string
    secrets:
      ARTIFACTORY_TOKEN:
        required: true
      CONTENTFUL_ACCESS_TOKEN:
        required: false
      CONTENTFUL_PREVIEW_ACCESS_TOKEN:
        required: false
      CONTENTFUL_SPACE_ID:
        required: false
      CONTENTFUL_ENVIRONMENT_ID:
        required: false

env:
  REACT_APP_ENV: ${{ inputs.REACT_APP_ENV }}
  ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  CONTENTFUL_PREVIEW_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_ACCESS_TOKEN }}
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ENVIRONMENT_ID: ${{ secrets.CONTENTFUL_ENVIRONMENT_ID }}
  NODE_OPTIONS: "--max_old_space_size=4096"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup NodeJS 18
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm config get cacheFolder)"

      - name: Cache pnpm dependencies
        uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: |
            ${{ steps.pnpm-cache-dir-path.outputs.dir }}
            **\node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Fetch main
        run: git fetch origin main

      - name: Test
        run: |
          RUN=CI pnpm nx affected:test --base=origin/main --parallel 5
          pnpm nx affected:lint --base=origin/main --parallel 5
          pnpm nx affected:build --base=origin/main --parallel 5
