name: Trigger Update Image Digest

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      directory_name:
        required: true
        type: string
      environment_dir:
        required: true
        type: string
      digest:
        required: true
        type: string
    secrets:
      UPDATE_MANIFEST_TOKEN:
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Parse env-org-map
        id: parse
        run: |
          python3 <<EOF
          import sys, os, yaml, json, os
          env = "${{ inputs.environment_dir }}"
          config_path = ".platform/env-org-map.yaml"
          use_default = True
          orgs = []
          default_org = os.environ.get('DEFAULT_DESTINATION_ORG')
          if os.path.exists(config_path):
              with open(config_path) as f:
                  config = yaml.safe_load(f) or {}
              env_config = config.get(env)
              if env_config is not None:
                  use_default = not env_config.get("externalOnly", False)
                  orgs = env_config.get("additionalOrgs", []) or []
          elif default_org:
              orgs = [default_org]
          print(f"useDefaultDirectory={str(use_default).lower()}", file=open(os.environ['GITHUB_OUTPUT'], 'a'))
          print(f"additionalOrgs={json.dumps(orgs)}", file=open(os.environ['GITHUB_OUTPUT'], 'a'))
          EOF

      - name: Trigger Update Image Digest
        run: |
          echo "Repository: ${{ inputs.repository }}"
          echo "Directory: ${{ inputs.directory_name }}"
          echo "Environment: ${{ inputs.environment_dir }}"
          echo "Digest: ${{ inputs.digest }}"
          echo "useDefaultDirectory: ${{ steps.parse.outputs.useDefaultDirectory }}"
          echo "additionalOrgs: ${{ steps.parse.outputs.additionalOrgs }}"
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.UPDATE_MANIFEST_TOKEN }}" \
            ${{ vars.PLATFORM_DISPATCH_URL }} \
            --fail-with-body \
            -d '{"event_type": "update-digest-2", "client_payload": {"repository": "${{ inputs.repository }}", "directory_name": "${{ inputs.directory_name }}", "environment_dir": "${{ inputs.environment_dir }}", "digest": "${{ inputs.digest }}", "useDefaultDirectory": ${{ steps.parse.outputs.useDefaultDirectory }}, "additionalOrgs": ${{ steps.parse.outputs.additionalOrgs }} }}'
